use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

platform :ios, '11.0'

target 'TangemSdkExample' do
  pod 'TangemSdk', :path => '../'
end

deployment_target = '11.0'

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
