# frozen_string_literal: true

PROJECT_NAME = 'TangemSdk/TangemSdk.xcodeproj'
SCHEMA_NAME = 'TangemSdk'
TEST_DEVICE = 'iPhone 16 Pro Max (18.5)' # Update when Xcode is updated

before_all do |lane, options|
  lanes_to_skip_bootstrap = [
    :update_translations,
  ]

  next if lanes_to_skip_bootstrap.include?(lane)

  # Xcode version overrides available only on CI
  if ENV['CI']&.downcase == 'true'
    if options[:xcode_version_override] && options[:xcode_version_override].empty?
      # Will use the Xcode version from the .xcode-version file
      xcodes(
        select_for_current_build_only: true
      )
    else
      xcodes(
        version: options[:xcode_version_override],
        select_for_current_build_only: true
      )
    end
  end

  ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '120'
  ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = '4'
end

lane :test do
  run_tests(
    project: PROJECT_NAME,
    scheme: SCHEMA_NAME,
    device: TEST_DEVICE,
    ensure_devices_found: true,
    skip_detect_devices: true,
    result_bundle: true,
    # Old Xcode output formatter, 'xcpretty',
    # doesn't work particularly well with the new build system and parallel testing output
    xcodebuild_formatter: 'xcbeautify',
    # 'xcbeautify' doesn't support HTML output type
    output_types: 'junit',
    clean: true
  )
end

lane :update_translations do |options|
  # Can't pass an array as a param for a lane,
  # see https://github.com/fastlane-community/fastlane-plugin-appicon/issues/41 for details
  languages = options[:languages]&.split(',')

  destination = options[:destination]
  unless destination && !destination.empty?
    UI.user_error!("Invalid destination path '#{destination}' for localization files")
  end

  bundle_install

  lokalise(
    destination: destination,
    replace_breaks: true,
    add_newline_eof: true,
    use_original: true,
    languages: languages,
    export_sort: 'a_z',
    export_empty_as: 'base'
  )
end
