name: Check if tag exists on PR to develop

on:
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  check-tag:
    name: Check if tag exists
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read VERSION file
      id: read-version-file
      run: |
        VERSION_NUMBER=$(cat VERSION)
        echo "version_number=${VERSION_NUMBER}" >> $GITHUB_OUTPUT

    - name: Check for Tag
      env:
        TAG: ${{ steps.read-version-file.outputs.version_number }}
      run: |
        if [ $(git tag -l "${TAG}") ]; then
          echo "Tag ${TAG} already exists. Please upgrade version in the 'VERSION' file"
          exit 1
        else
          echo "Tag ${TAG} does not exist"
        fi
