name: Check if tag exists on PR to develop

on:
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  check-tag:
    name: Check if tag exists
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # When using Github runner images, the preferred way of setting the Ruby version is to use this official action instead of using rvm/rbenv
    - name: Install Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc  # v1.202.0

    - name: Read VERSION file
      id: read-version-file
      run: |
        VERSION_NUMBER=$(cat VERSION)
        echo "version_number=${VERSION_NUMBER}" >> $GITHUB_OUTPUT

    - name: Check for Tag
      env:
        TAG: ${{ steps.read-version-file.outputs.version_number }}
      run: |
        if [ $(git tag -l "${TAG}") ]; then
          echo "Tag ${TAG} already exists. Please upgrade version in the 'VERSION' file"
          exit 1
        else
          echo "Tag ${TAG} does not exist"
        fi
