name: Create release branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 1.3.0)'
        required: true

jobs:
  createrelease:
    name: Create release branch
    runs-on: ubuntu-latest
    #if: contains(github.ref, 'develop') # Only for develop branch
    steps:
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
      
    - name: Initialize mandatory git config
      run: |
       git config user.name "Tangem Bot"
       git config user.email mobile@tangem.com
       
    - name: Change version
      run: |
       echo ${{ github.event.inputs.versionName }} > VERSION
       git add VERSION
       git commit -m "Prepare release v${{ github.event.inputs.versionName }}"
       
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
