name: Neutral Build

on:
  push:
    branches: 
    #- 'develop'
    - 'feature/IOS-9112_gh_enterprise_fixes'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_IOS }}

jobs:
  tag:
    name: Create tag
    runs-on: macOS-latest
    steps:
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.extract_branch.outputs.branch }}-${{ github.run_number }}",
            sha: context.sha
          })

    - name: Build notification
      if: always()
      uses: adamkdean/simple-slack-notify@master
      with:
        channel: '#development-ios'
        status: ${{ job.status }}
        success_text: 'Card SDK tag (${{ steps.extract_branch.outputs.branch }}-${{ github.run_number }}) has been created.'
        failure_text: 'GitHub Action #${{ github.run_number }} failed. Tag has not been not created.'
        cancelled_text: 'GitHub Action #${{ github.run_number }} was cancelled'
        fields: |
          [{"title": "TAG", "value": "${{ steps.extract_branch.outputs.branch }}-${{ github.run_number }}"},
          {"title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
