name: Publish Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:
     
jobs:
  merges:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
  
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6  

      - name: Bundle Install
        run: bundle install
      
      - name: Prepare variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
    
      - name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          commitish: master
          body_path: CHANGELOG
          draft: false
          prerelease: false    
            
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        
      - name: Create pull request to develop
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          base: develop
          branch: master
          labels: automatic
