name: Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Tests
      run: bundle exec fastlane test
