name: Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install CocoaPods
      run: |
        ls -la
        cd tangem-sdk-ios
        pod install
    - name: Tests
      run: fastlane test
